//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoresPlace_Front.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StoresPlace_Front.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept all terms ,conditions and privacy policy.
        /// </summary>
        internal static string Accept_Terms {
            get {
                return ResourceManager.GetString("Accept_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new coupoun.
        /// </summary>
        internal static string Add_New_Coupoun {
            get {
                return ResourceManager.GetString("Add_New_Coupoun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new offer.
        /// </summary>
        internal static string Add_New_Offer {
            get {
                return ResourceManager.GetString("Add_New_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your store.
        /// </summary>
        internal static string Add_New_Store {
            get {
                return ResourceManager.GetString("Add_New_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Them.
        /// </summary>
        internal static string App_Them {
            get {
                return ResourceManager.GetString("App_Them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your account?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_your_account {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete your store.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_your_store {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_your_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaiting order receipt.
        /// </summary>
        internal static string Awaiting_order_receipt {
            get {
                return ResourceManager.GetString("Awaiting_order_receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t complete your registration.
        /// </summary>
        internal static string Cant_Complete_your_register {
            get {
                return ResourceManager.GetString("Cant_Complete_your_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant send complaint.
        /// </summary>
        internal static string Cant_send_Complain {
            get {
                return ResourceManager.GetString("Cant_send_Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant send order.
        /// </summary>
        internal static string Cant_send_Order {
            get {
                return ResourceManager.GetString("Cant_send_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Items.
        /// </summary>
        internal static string Choose_Items {
            get {
                return ResourceManager.GetString("Choose_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose best method to paid.
        /// </summary>
        internal static string Chosee_best_methoud_to_paid {
            get {
                return ResourceManager.GetString("Chosee_best_methoud_to_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes Scheduling.
        /// </summary>
        internal static string Clothes_scheduling {
            get {
                return ResourceManager.GetString("Clothes_scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing available for scheduling.
        /// </summary>
        internal static string Clothing_available_for_scheduling {
            get {
                return ResourceManager.GetString("Clothing_available_for_scheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Number.
        /// </summary>
        internal static string Commercial_Number {
            get {
                return ResourceManager.GetString("Commercial_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complain.
        /// </summary>
        internal static string Complain {
            get {
                return ResourceManager.GetString("Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complain sent Successfully.
        /// </summary>
        internal static string Complain_sent_Successfully {
            get {
                return ResourceManager.GetString("Complain_sent_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complains.
        /// </summary>
        internal static string Complains {
            get {
                return ResourceManager.GetString("Complains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue as guest.
        /// </summary>
        internal static string Continue_As_Guest {
            get {
                return ResourceManager.GetString("Continue_As_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 966.
        /// </summary>
        internal static string Country_Code {
            get {
                return ResourceManager.GetString("Country_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        internal static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string Create_Account {
            get {
                return ResourceManager.GetString("Create_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved failed.
        /// </summary>
        internal static string Data_saved_failed {
            get {
                return ResourceManager.GetString("Data_saved_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        internal static string Data_Saved_Successfully {
            get {
                return ResourceManager.GetString("Data_Saved_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        internal static string Delete_Account {
            get {
                return ResourceManager.GetString("Delete_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store.
        /// </summary>
        internal static string Delete_Store {
            get {
                return ResourceManager.GetString("Delete_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Dilevry {
            get {
                return ResourceManager.GetString("Dilevry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel this order.
        /// </summary>
        internal static string Do_you_want_to_cancel_this_order {
            get {
                return ResourceManager.GetString("Do_you_want_to_cancel_this_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollapp.
        /// </summary>
        internal static string Dollapp {
            get {
                return ResourceManager.GetString("Dollapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollapp.
        /// </summary>
        internal static string Dollappy {
            get {
                return ResourceManager.GetString("Dollappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawers.
        /// </summary>
        internal static string Drawers {
            get {
                return ResourceManager.GetString("Drawers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is not correct. Please check and try again.
        /// </summary>
        internal static string Email_or_password_not_correct_please_check_then_try_again {
            get {
                return ResourceManager.GetString("Email_or_password_not_correct_please_check_then_try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening the website.
        /// </summary>
        internal static string Error_opening_the_website {
            get {
                return ResourceManager.GetString("Error_opening_the_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string Expiration_Date {
            get {
                return ResourceManager.GetString("Expiration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string In_Progress {
            get {
                return ResourceManager.GetString("In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the laundry.
        /// </summary>
        internal static string In_the_laundry {
            get {
                return ResourceManager.GetString("In_the_laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internt.
        /// </summary>
        internal static string Internt {
            get {
                return ResourceManager.GetString("Internt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Laundry {
            get {
                return ResourceManager.GetString("Laundry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Store.
        /// </summary>
        internal static string Local_Store {
            get {
                return ResourceManager.GetString("Local_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Stores.
        /// </summary>
        internal static string Local_Stores {
            get {
                return ResourceManager.GetString("Local_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location access is required for this feature. Please enable location services in your device settings.
        /// </summary>
        internal static string Location_access {
            get {
                return ResourceManager.GetString("Location_access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following information to finish the registration process.
        /// </summary>
        internal static string Log_In_Desc {
            get {
                return ResourceManager.GetString("Log_In_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Store.
        /// </summary>
        internal static string My_Store {
            get {
                return ResourceManager.GetString("My_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My stores.
        /// </summary>
        internal static string My_Stores {
            get {
                return ResourceManager.GetString("My_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name .
        /// </summary>
        internal static string Namee {
            get {
                return ResourceManager.GetString("Namee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Complaint.
        /// </summary>
        internal static string New_Complain {
            get {
                return ResourceManager.GetString("New_Complain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No coupns.
        /// </summary>
        internal static string No_Coupns {
            get {
                return ResourceManager.GetString("No_Coupns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No offers.
        /// </summary>
        internal static string No_offers {
            get {
                return ResourceManager.GetString("No_offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note to Identify the Piece:
        ///For example, a red T-shirt with black stripes.
        /// </summary>
        internal static string Note_to_Identify_the_Piece {
            get {
                return ResourceManager.GetString("Note_to_Identify_the_Piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of store visits.
        /// </summary>
        internal static string Number_of_store_visits {
            get {
                return ResourceManager.GetString("Number_of_store_visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        internal static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Store.
        /// </summary>
        internal static string Online_Store {
            get {
                return ResourceManager.GetString("Online_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Stores.
        /// </summary>
        internal static string Online_Stores {
            get {
                return ResourceManager.GetString("Online_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Canceled Successfully.
        /// </summary>
        internal static string Order_Canceled_Successfully {
            get {
                return ResourceManager.GetString("Order_Canceled_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Details.
        /// </summary>
        internal static string Order_Details {
            get {
                return ResourceManager.GetString("Order_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Sent Successfully.
        /// </summary>
        internal static string Order_Sent_Successfully {
            get {
                return ResourceManager.GetString("Order_Sent_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Sent Successfully Number.
        /// </summary>
        internal static string Order_Sent_Successfully_Number {
            get {
                return ResourceManager.GetString("Order_Sent_Successfully_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        internal static string Paid {
            get {
                return ResourceManager.GetString("Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount to be paid.
        /// </summary>
        internal static string Paid_Amount {
            get {
                return ResourceManager.GetString("Paid_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        internal static string Password_not_matched {
            get {
                return ResourceManager.GetString("Password_not_matched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay a percentage of purchases.
        /// </summary>
        internal static string Pay_a_percentage_of_purchases {
            get {
                return ResourceManager.GetString("Pay_a_percentage_of_purchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment per piece.
        /// </summary>
        internal static string Payment_per_piece {
            get {
                return ResourceManager.GetString("Payment_per_piece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Order.
        /// </summary>
        internal static string Place_Order {
            get {
                return ResourceManager.GetString("Place_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that you have an internet connection.
        /// </summary>
        internal static string Please_Check_Intenet {
            get {
                return ResourceManager.GetString("Please_Check_Intenet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check webiste link.
        /// </summary>
        internal static string Please_Check_Webiste_link {
            get {
                return ResourceManager.GetString("Please_Check_Webiste_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your information to finish the update process.
        /// </summary>
        internal static string Please_complete_to_update {
            get {
                return ResourceManager.GetString("Please_complete_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a least 24 letter.
        /// </summary>
        internal static string Please_enter_a_least_24_letter {
            get {
                return ResourceManager.GetString("Please_enter_a_least_24_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter a valid password.
        /// </summary>
        internal static string please_enter_a_valid_password {
            get {
                return ResourceManager.GetString("please_enter_a_valid_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter another email; this email already exists.
        /// </summary>
        internal static string Please_enter_another_email_this_email_is_Exist {
            get {
                return ResourceManager.GetString("Please_enter_another_email_this_email_is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter another phone number; this phone number already exists..
        /// </summary>
        internal static string Please_enter_another_phone_this_phone_is_Exist {
            get {
                return ResourceManager.GetString("Please_enter_another_phone_this_phone_is_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the price.
        /// </summary>
        internal static string Please_enter_the_price {
            get {
                return ResourceManager.GetString("Please_enter_the_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        internal static string Please_Enter_Valid_Email {
            get {
                return ResourceManager.GetString("Please_Enter_Valid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        internal static string Please_Enter_Valid_Phone {
            get {
                return ResourceManager.GetString("Please_Enter_Valid_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your complaint here.
        /// </summary>
        internal static string Please_enter_your_Complain_here {
            get {
                return ResourceManager.GetString("Please_enter_your_Complain_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your coupon details.
        /// </summary>
        internal static string Please_enter_your_Coupon_details {
            get {
                return ResourceManager.GetString("Please_enter_your_Coupon_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email and password to access your account.
        /// </summary>
        internal static string Please_enter_your_email_and_password_to_access_your_account {
            get {
                return ResourceManager.GetString("Please_enter_your_email_and_password_to_access_your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your offer details.
        /// </summary>
        internal static string Please_enter_your_offer_details {
            get {
                return ResourceManager.GetString("Please_enter_your_offer_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields before continuing.
        /// </summary>
        internal static string Please_fill_all_fields_before_continue {
            get {
                return ResourceManager.GetString("Please_fill_all_fields_before_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select region.
        /// </summary>
        internal static string Please_Select_a_region {
            get {
                return ResourceManager.GetString("Please_Select_a_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 8 items.
        /// </summary>
        internal static string Please_select_at_least_8_items {
            get {
                return ResourceManager.GetString("Please_select_at_least_8_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one item.
        /// </summary>
        internal static string Please_select_at_least_one_items {
            get {
                return ResourceManager.GetString("Please_select_at_least_one_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select city.
        /// </summary>
        internal static string Please_Select_city {
            get {
                return ResourceManager.GetString("Please_Select_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select district.
        /// </summary>
        internal static string Please_Select_district {
            get {
                return ResourceManager.GetString("Please_Select_district", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location.
        /// </summary>
        internal static string Please_Select_Location {
            get {
                return ResourceManager.GetString("Please_Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select a region.
        /// </summary>
        internal static string Please_Select_region {
            get {
                return ResourceManager.GetString("Please_Select_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your region.
        /// </summary>
        internal static string Please_select_your_region {
            get {
                return ResourceManager.GetString("Please_select_your_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your store category.
        /// </summary>
        internal static string Please_select_your_store_Category {
            get {
                return ResourceManager.GetString("Please_select_your_store_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your store type.
        /// </summary>
        internal static string Please_select_your_store_type {
            get {
                return ResourceManager.GetString("Please_select_your_store_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in to complete the process.
        /// </summary>
        internal static string Please_sign_in_to_Complete_process {
            get {
                return ResourceManager.GetString("Please_sign_in_to_Complete process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Order.
        /// </summary>
        internal static string Previous_Order {
            get {
                return ResourceManager.GetString("Previous_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Detiles.
        /// </summary>
        internal static string Price_Detiles {
            get {
                return ResourceManager.GetString("Price_Detiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        internal static string Price_List {
            get {
                return ResourceManager.GetString("Price_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productive families.
        /// </summary>
        internal static string productive_families {
            get {
                return ResourceManager.GetString("productive_families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Date.
        /// </summary>
        internal static string Receiving_Date {
            get {
                return ResourceManager.GetString("Receiving_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        internal static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remain.
        /// </summary>
        internal static string Remain {
            get {
                return ResourceManager.GetString("Remain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove store.
        /// </summary>
        internal static string Remove_store {
            get {
                return ResourceManager.GetString("Remove_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter Password.
        /// </summary>
        internal static string RePassword {
            get {
                return ResourceManager.GetString("RePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return time.
        /// </summary>
        internal static string Return_time {
            get {
                return ResourceManager.GetString("Return_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  r.s.
        /// </summary>
        internal static string Ryial {
            get {
                return ResourceManager.GetString("Ryial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save store.
        /// </summary>
        internal static string Save_Store {
            get {
                return ResourceManager.GetString("Save_Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved stores.
        /// </summary>
        internal static string Saved_stores {
            get {
                return ResourceManager.GetString("Saved_stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scheduled.
        /// </summary>
        internal static string scheduled {
            get {
                return ResourceManager.GetString("scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Clothes.
        /// </summary>
        internal static string scheduled_clothes {
            get {
                return ResourceManager.GetString("scheduled_clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Items.
        /// </summary>
        internal static string Select_Items {
            get {
                return ResourceManager.GetString("Select_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Location.
        /// </summary>
        internal static string Select_Location {
            get {
                return ResourceManager.GetString("Select_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Order.
        /// </summary>
        internal static string Select_Order {
            get {
                return ResourceManager.GetString("Select_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the items you want to pay for.
        /// </summary>
        internal static string Select_the_items_you_want_to_pay_for {
            get {
                return ResourceManager.GetString("Select_the_items_you_want_to_pay_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell your store.
        /// </summary>
        internal static string Sell_your_store {
            get {
                return ResourceManager.GetString("Sell_your_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send New Clothes.
        /// </summary>
        internal static string Send_New_Clothes {
            get {
                return ResourceManager.GetString("Send_New_Clothes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Order.
        /// </summary>
        internal static string Send_Order {
            get {
                return ResourceManager.GetString("Send_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Introduction.
        /// </summary>
        internal static string Service_Introduction {
            get {
                return ResourceManager.GetString("Service_Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        internal static string Service_Request {
            get {
                return ResourceManager.GetString("Service_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Sigh_Up {
            get {
                return ResourceManager.GetString("Sigh_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        internal static string Sign_Out {
            get {
                return ResourceManager.GetString("Sign_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Now.
        /// </summary>
        internal static string Start_Now {
            get {
                return ResourceManager.GetString("Start_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store created successfully.
        /// </summary>
        internal static string Store_created_successfully {
            get {
                return ResourceManager.GetString("Store_created_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type.
        /// </summary>
        internal static string Store_Type {
            get {
                return ResourceManager.GetString("Store_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string Stores {
            get {
                return ResourceManager.GetString("Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores for sale.
        /// </summary>
        internal static string Stores_for_sale {
            get {
                return ResourceManager.GetString("Stores_for_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Conditions.
        /// </summary>
        internal static string Terms_Conditions {
            get {
                return ResourceManager.GetString("Terms_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cart is empty.
        /// </summary>
        internal static string The_cart_is_empty {
            get {
                return ResourceManager.GetString("The_cart_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been successfully submitted.
        /// </summary>
        internal static string The_request_has_been_successfully_submitted {
            get {
                return ResourceManager.GetString("The_request_has_been_successfully_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was not submitted successfully.
        /// </summary>
        internal static string The_request_was_not_submitted_successfully {
            get {
                return ResourceManager.GetString("The_request_was_not_submitted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been added successfully.
        /// </summary>
        internal static string The_store_has_been_added_successfully {
            get {
                return ResourceManager.GetString("The_store_has_been_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been deleted successfully.
        /// </summary>
        internal static string The_store_has_been_deleted_successfully {
            get {
                return ResourceManager.GetString("The_store_has_been_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been remove successfully.
        /// </summary>
        internal static string The_store_has_been_remove_successfully {
            get {
                return ResourceManager.GetString("The_store_has_been_remove_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has not been deleted successfully.
        /// </summary>
        internal static string The_store_has_not_been_deleted_successfully {
            get {
                return ResourceManager.GetString("The_store_has_not_been_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store was not added successfully.
        /// </summary>
        internal static string The_store_was_not_added_successfully {
            get {
                return ResourceManager.GetString("The_store_was_not_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store was not remove successfully.
        /// </summary>
        internal static string The_store_was_not_remove_successfully {
            get {
                return ResourceManager.GetString("The_store_was_not_remove_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no stores saved.
        /// </summary>
        internal static string There_are_no_stores_saved {
            get {
                return ResourceManager.GetString("There_are_no_stores_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Information.
        /// </summary>
        internal static string Update_Information {
            get {
                return ResourceManager.GetString("Update_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the app is available.                                              Please update to continue.
        /// </summary>
        internal static string Update_Version {
            get {
                return ResourceManager.GetString("Update_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Deleted Successfully.
        /// </summary>
        internal static string User_Deleted_Successfully {
            get {
                return ResourceManager.GetString("User_Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not deleted successfully. Please contact us.
        /// </summary>
        internal static string User_was_not_deleted_Successfully_please_contact_with_us {
            get {
                return ResourceManager.GetString("User_was_not_deleted_Successfully_please_contact_with_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to internet.
        /// </summary>
        internal static string You_don_t_have_access_to_internet {
            get {
                return ResourceManager.GetString("You_don\'t_have_access_to_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you don&apos;t have any orders.
        /// </summary>
        internal static string you_dont_have_any_order {
            get {
                return ResourceManager.GetString("you_dont_have_any_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your complain has been sent successfully number.
        /// </summary>
        internal static string your_complain_has_been_sent_successfully_Complain_number {
            get {
                return ResourceManager.GetString("your_complain_has_been_sent_successfully_Complain_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon has been added falied.
        /// </summary>
        internal static string Your_Coupon_has_been_added_falied {
            get {
                return ResourceManager.GetString("Your_Coupon_has_been_added_falied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon has been added successfully.
        /// </summary>
        internal static string Your_Coupon_has_been_added_successfully {
            get {
                return ResourceManager.GetString("Your_Coupon_has_been_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer has failed to be added..
        /// </summary>
        internal static string Your_offer_has_been_added_falied {
            get {
                return ResourceManager.GetString("Your_offer_has_been_added_falied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer has been added successfully.
        /// </summary>
        internal static string Your_offer_has_been_added_successfully {
            get {
                return ResourceManager.GetString("Your_offer_has_been_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order cancel failed.
        /// </summary>
        internal static string your_order_cancel_failed {
            get {
                return ResourceManager.GetString("your_order_cancel_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User was not deleted successfully. Please contact us.
        /// </summary>
        internal static string your_order_cancel_successfully {
            get {
                return ResourceManager.GetString("your_order_cancel_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order has been canceled successfully number .
        /// </summary>
        internal static string your_order_has_been_canceled_successfully_number {
            get {
                return ResourceManager.GetString("your_order_has_been_canceled_successfully_number", resourceCulture);
            }
        }
    }
}
